--- 
artifacts: 
  files: 
    - web.py
    - test_app.py
    - appspec.yml
    - templates/layout.html
    - templates/test.html
    - scripts/mkdir.sh
    - scripts/start_flask.sh
    - scripts/stop_flask1.sh
    - scripts/stop_flask.py
    - scripts/stop_flask.sh
phases: 
  build: 
    commands: 
      - "echo Build started on `date`"
      - "echo Compiling the Python code..."
      - "python test_app.py"
  install: 
    commands: 
      - "python -m pip install Flask"
  post_build: 
    commands: 
      - "echo Build completed on `date`"
version: 0.2
